export const quotes = [
  "Drift into dreams with our soothing sounds.",
  "Wrap yourself in calm.",
  "Rest easy, sleep soundly.",
  "Breathe deep, sleep well.",
  "Find your peace at night.",
  "Quiet your mind, embrace sleep.",
  "Soothe your soul with sound.",
  "Restful nights await you.",
  "Sink into serene slumber.",
  "Soft whispers of night's calm.",
  "Sharpen your focus, find your flow.",
  "Tune into productivity.",
  "Fuel your mind, focus your energy.",
  "Study smart, stay inspired.",
  "Focus deeply, learn easily.",
  "Soundtrack your study session.",
  "Power through with clarity.",
  "Calm focus fuels creativity.",
  "Concentration meets inspiration.",
  "Harness sound, master your mind.",
  "Elevate your work energy.",
  "Conquer your to-do list with flow.",
  "Work deeply, achieve more.",
  "Get in the zone, stay productive.",
  "Find your rhythm, master your tasks.",
  "Stay sharp, stay ahead.",
  "Fuel focus with every note.",
  "Soundtrack your success.",
  "Work smarter, not harder.",
  "Laser focus at your fingertips.",
  "Center yourself, find inner calm.",
  "Meditate to the sound of serenity.",
  "Breathe, listen, relax.",
  "Stillness is power.",
  "Let sound guide your breath.",
  "Find your moment of peace.",
  "Silence the mind, awaken the soul.",
  "Unwind with mindful melodies.",
  "Presence in every note.",
  "Flow into the present moment.",
  "Rise with purpose, flow with ease.",
  "Your journey starts with one sound.",
  "Chase dreams, conquer goals.",
  "Find clarity, ignite your spark.",
  "Empower your mind, energize your day.",
  "Take a breath, take the leap.",
  "Every note is a new beginning.",
  "Stay grounded, keep moving forward.",
  "Balance ambition with calm.",
  "Let sound be your guide.",
  "Whispers of calm guide you to sleep.",
  "Quiet the world, drift within.",
  "Gentle sounds, peaceful nights.",
  "A lullaby for your busy mind.",
  "Slip into a restful state.",
  "Embrace stillness under the stars.",
  "Soothe your soul, one sound at a time.",
  "Breathe in calm, exhale stress.",
  "Where silence meets serenity.",
  "Your night, your calm, your rhythm.",
  "Dive deep, focus fully.",
  "Fuel your mind, focus sharp.",
  "Stay grounded, stay inspired.",
  "Concentration starts here.",
  "Clarity in every note.",
  "Anchor your thoughts, elevate your mind.",
  "Study with purpose, sound with intention.",
  "Find focus in the flow.",
  "Stay clear, stay sharp.",
  "Flow through your study session.",
  "Unlock deep focus with sound.",
  "Create your calm workspace.",
  "Inspire your productivity flow.",
  "Find your groove, work smarter.",
  "Power up your focus, tune in.",
  "Quiet distractions, fuel progress.",
  "Sounds that spark productivity.",
  "Stay steady, stay sharp.",
  "Clarity for your creative mind.",
  "Craft your focus soundtrack.",
  "Find stillness in sound.",
  "Let music guide your breath.",
  "Unfold your mind's quiet corners.",
  "Calm is a sound away.",
  "Inhale peace, exhale tension.",
  "Every note is a step inward.",
  "Sound meets stillness.",
  "Harmony of mind and music.",
  "Let the present moment sing.",
  "Flow with mindful melodies.",
  "Let today's sound spark tomorrow's success.",
  "Rise with rhythm, flow with purpose.",
  "Soundtrack your goals, conquer your day.",
  "Stay inspired, stay present.",
  "Momentum comes from within.",
  "Breathe in strength, exhale doubt.",
  "Let music be your momentum.",
  "A sound for every journey.",
  "Unlock your potential with calm.",
  "Empower focus, embrace possibility."
];
